### ISSUE TITLE
running as a cross-platform stand-alone?

### ISSUE THREAD

**Issue by poppu-mtg** [poppu-mtg/StackIt#10]
is it even possible? I have looked into Nuitka, but not sure this is the best tool out there?

**Comment by JeffHoogland** [comment]
Are you interested in creating / packaging a simple GUI for using the tool? If so what would you want it to have? Would you like a file selector to point to a text file, a text area to paste decklists into, or maybe both options? It wouldn't take too long to build something simple and effective in Qt that would be cross platform.

**Comment by silasary** [comment]
As it currently stands, the tool needs to have a text file, and the filename affects the name of the deck.

As such, the tool would either need to just be a file selector, or it would need to save the decklist into a file.

With that said, I'd say the tool isn't mature enough yet, and we may end up changing things.
