### ISSUE TITLE
handling split cards

### ISSUE THREAD

**Issue by poppu-mtg** [poppu-mtg/StackIt#17]
e.g. Beck // Call : first modification is to change `get_card_info` in  `scraper.py` so that it reads:

>if line.find(' / ') != -1:  

the current version does not have the spaces around the separator, forcing split cards to be treated as if they were pointing to a specific art. I tested it real quick and adding the spaces makes sure that at least the card is recognized.

After that is the treatment of the two CMC's as found in the database. I have a couple of ideas but need to see sample HTML info from cmcweb first...

**Comment by silasary** [comment]
Yeah, Split cards are always a pain.
I'd say we wait until #16 is done, so we're at least getting sanitized data, rather than using the HTML parsing.

It's worth noting that the MtgGoldfish overlay doesn't give split-cards any mana cost at all. (see https://www.youtube.com/watch?v=QYmEfOinbLk)

**Comment by poppu-mtg** [comment]
Closing this issue for now - HTML parsing was enough to set it up.

If we eventually change the card info database, I am not expecting the split card names to be *that* different from what is already coded in.
