### ISSUE TITLE
Mana symbols with better resolution?

### ISSUE THREAD

**Issue by poppu-mtg** [poppu-mtg/StackIt#19]
All I keep finding is .svg files, would ideally like .png to just have the "round" symbols.

Any idea?

**Comment by silasary** [comment]
Is there a reason we can't use SVG?
It should be the ideal format.

**Comment by poppu-mtg** [comment]
I think I read somewhere that opening SVG files would require switching to python3, but I could be wrong

**Comment by silasary** [comment]
I'll have a look into it.  But you're probably right - python2 is pretty frustrating.
