### ISSUE TITLE
Hex Support?

### ISSUE THREAD

**Issue by silasary** [poppu-mtg/StackIt#22]
As requested [on twitter](https://twitter.com/akaT3CK/status/842872152764293120).

== Method 1: Scraping ==

At first glance, we have the following things:
* [Decklist page](http://hexpvptools.net/constructed/ladder/deck/1cbe7803-0c8e-7b1e-4533-2fa96353250e).  This is the user-facing decklist.
* [json decklist](http://hexpvptools.net/deck/1cbe7803-0c8e-7b1e-4533-2fa96353250e.json?group=cost).  This is a machine readable blob, and what the above page uses to retrieve images.
* Card images.  These are located at `http://hexpvptools.net/images/cards/small/{guid}.jpg`, where guid is specified in the json blob.

What we're missing:
* Card names.
* Card costs.

== Method 2: Sync API ==

This one is more complex, and requires the user to do a lot more setup. 

I'll probably need to download the game before I can decide whether it actually lets us do what we need. (The documentation is really unclear)

**Comment by silasary** [comment]
Ok, so the Sync API is super weird.  But it might be able to work for us.
Assuming it gives us the names and costs.

**Comment by poppu-mtg** [comment]
Same here, I would have to get familiar with the game before deciding which way to go.

**Comment by poppu-mtg** [comment]
I think I found a way: I am creating a dictionary from the card name to the web address of its large picture. Took a bit of manipulation, but I have a gigantic html web page saved with the entire checklist in it.

**Comment by silasary** [comment]
That sounds horrifying.

**Comment by poppu-mtg** [comment]
it wasn't that bad, really - needed to learn a bit about the game too, to be sure to cover most of the options
