### ISSUE TITLE
Not Generating MTG Deck on Ubuntu 16.04 with Py2

### ISSUE THREAD

**Issue by JeffHoogland** [poppu-mtg/StackIt#39]
Getting this error output when trying to generate a MTG deck with the latest git source using python 2:

List(game=1, mainboard=[Card(name='Creeping Tar Pit', set=u'WWK', cost='*', quantity='3x', collector_num=u'134'), Card(name='Darkslick Shores', set=u'SOM', cost='*', quantity='2x', collector_num=u'226'), Card(name='Island', set='uh', cost='*', quantity='2x', collector_num=None), Card(name='Mutavault', set=u'M14', cost='*', quantity='4x', collector_num=u'12'), Card(name='Polluted Delta', set=u'EXP', cost='*', quantity='4x', collector_num=u'45'), Card(name='Secluded Glen', set=u'LRW', cost='*', quantity='4x', collector_num=u'271'), Card(name='Sunken Ruins', set=u'EXP', cost='*', quantity='2x', collector_num=u'280'), Card(name='Swamp', set='uh', cost='*', quantity='2x', collector_num=None), Card(name='Watery Grave', set=u'EXP', cost='*', quantity='1x', collector_num=u'286'), Card(name='Bitterblossom', set=u'MM2', cost='1B', quantity='4x', collector_num=u'59'), Card(name='Disfigure', set=u'DDR', cost='B', quantity='1x', collector_num=u'87'), Card(name='Fatal Push', set=u'AER', cost='B', quantity='4x', collector_num=u'57'), Card(name='Go for the Throat', set=u'MBS', cost='1B', quantity='2x', collector_num=u'138'), Card(name='Murderous Cut', set=u'KTK', cost='4B', quantity='1x', collector_num=u'81'), Card(name='Spell Snare', set=u'MMA', cost='U', quantity='2x', collector_num=u'33'), Card(name='Snapcaster Mage', set=u'ISD', cost='1U', quantity='4x', collector_num=u'78'), Card(name='Spellstutter Sprite', set=u'MMA', cost='1U', quantity='4x', collector_num=u'129'), Card(name='Vendilion Clique', set=u'MM2', cost='1UU', quantity='3x', collector_num=u'58'), Card(name='Inquisition of Kozilek', set=u'CN2', cost='B', quantity='4x', collector_num=u'115'), Card(name="Smuggler's Copter", set=u'KLD', cost='2', quantity='4x', collector_num=u'235'), Card(name='Liliana of the Veil', set=u'ISD', cost='1BB', quantity='3x', collector_num=u'105')], sideboard=[], commander=[])
Traceback (most recent call last):
  File "StackIt.py", line 390, in <module>
    main(sys.argv[1])
  File "StackIt.py", line 280, in main
    draw_mtg_card(card, nstep)
  File "StackIt.py", line 129, in draw_mtg_card
    draw = ImageDraw.Draw(cut)
  File "/usr/lib/python2.7/dist-packages/PIL/ImageDraw.py", line 323, in Draw
    return ImageDraw(im, mode)
  File "/usr/lib/python2.7/dist-packages/PIL/ImageDraw.py", line 59, in __init__
    im.load()
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 1961, in load
    self.im = self.im.crop(self.__crop)
TypeError: integer argument expected, got float

**Comment by silasary** [comment]
Hmm.  I think I see your problem.  Can you post the original decklist?  (And does it have `2x CARDNAME` rather than just `2 CARDNAME`?)

**Comment by JeffHoogland** [comment]
Not sure what I actually pasted sorry. Was 2x CARDNAME

**Comment by silasary** [comment]
Yeah, for whatever reason, that formatting wasn't supported.  Fixing that now :)
