### ISSUE TITLE
Make sure that the tests are actually working properly

### ISSUE THREAD

**Issue by silasary** [poppu-mtg/StackIt#57]
Somehow we've had a broken build for quite a while (see #56), but the automated tests weren't catching it.

Find out why.

**Comment by poppu-mtg** [comment]
that is strange - Jeff has been using the latest build to generate HEX lists (albeit regular ones, no scrolling ones) and there did not seem to be any issues. I'll ping him to see if he had to change anything.

**Comment by JeffHoogland** [comment]
I actually maintain a local copy with some custom font settings for my use with my API tool - so I haven't tried your latest build in awhile. 

Source looks to be 4~ months old. I just tend to leave dependency versions alone unless they add a few feature I need.

https://github.com/JeffHoogland/HexAPIStreamingTools/tree/master/StackIt

**Comment by silasary** [comment]
I've finally gotten around to implementing #41, so hopefully you won't need to maintain a custom fork just for font reasons.

**Comment by silasary** [comment]
@JeffHoogland I looked over your fork, and it looks like you've made at least one other [change](https://github.com/JeffHoogland/HexAPIStreamingTools/commit/25966a768c0a3d61ce7edecfbbece4ab09ffa2ad#diff-1ffd33e76fdd9135a83dfc1da8881304R236)

Would it be possible to get you to send a PR with all your changes?

EDIT:  I tried to create a diff, but it appears that your base commit varies from file to file.

**Comment by JeffHoogland** [comment]
That is the only change I made outside of fonts. Is it possible to add support for more icons in the deck name like we have for [RUBY] [SAPPHIRE] and such now? Hex lets us save different icons like [ATK] and [INVINCIBLE] in the deck name. My hack was to just remove it from the title, but ideally they'd show the images like they do in the game.

**Comment by silasary** [comment]
I'll see what I can do. 

Is it just ATK and INVINCIBLE or are there any others?

**Comment by JeffHoogland** [comment]
There are a few - do you have an email I can send the image files too? Doesn't look like I can attach a zip file here.

**Comment by silasary** [comment]
I notice that in the files you've given me, the image is called `Attack`, but in your decklists, it's called `ATK`.

Is there a list of canonical names?

**Comment by JeffHoogland** [comment]
That is the only short hand one I believe. They will also always be all capital in the decklist title.
