### ISSUE TITLE
Give Option to Shift Decklist Name Starting Position

### ISSUE THREAD

**Issue by JeffHoogland** [poppu-mtg/StackIt#59]
When I use Hex stackits on stream I often have the champion cut off screen since it is redundant information. It would be ideal if the deck title is shifted over a bit to start where the card names start.

**Comment by silasary** [comment]
That should be possible after my the next bit of refactoring I'm doing.  
Basically, we currently use different code paths for hex and mtg/pkmn.  As an attempt to make mtg commander decks work, I want the "hex" layout.  

So I'm currently making it a distinction between "Show Commander" or not.  After which it should be easy to disable showing the champion for Hex lists.

**Comment by JeffHoogland** [comment]
I'd rather shift the deck name start point than hide the champion. That way I can use the same image for on stream and for tweeting.

**Comment by silasary** [comment]
So you want the deck name to be indented by the width of the champion column?

**Comment by JeffHoogland** [comment]
Correct.

**Comment by silasary** [comment]
How does this look?
![atk blood ruby reanimator](https://user-images.githubusercontent.com/194254/28549284-5bc51274-711c-11e7-947f-7517240acb2e.png)

**Comment by JeffHoogland** [comment]
That is fantastic.
