### ISSUE TITLE
Cache downloaded card images

### ISSUE THREAD

**Issue by silasary** [poppu-mtg/StackIt#6]
Currently, we delete card scans once we've used them (And then redownload them next run)
This is a terrible waste of bandwidth, and we should try to cache them where possible.

**Comment by poppu-mtg** [comment]
I wasn't quite sure how to handle the scans once downloaded. I guess the next best thing is to create a directory/repository of scans, archived by set name?

**Comment by silasary** [comment]
I was thinking a subdirectory called `images`, then putting `{cardname}_{set}.jpg` in there.

**Comment by poppu-mtg** [comment]
That is pretty much what I had in mind, yes - that way it avoids creating subdirectories for each set. I can then see each instance of the script first creating a list of the existing scan and then applying an `if {currentname} in {list_of_scans}` and take it from there.

Let me say again how grateful I am for all your comments and feedback. At first this was just a small script that I intended to use for myself, for blogging and/or streaming. To see it develop into what it is today is very gratifying, and I have you to thank for that!

**Comment by silasary** [comment]
Fixed by #7
