### ISSUE TITLE
os.rename error on 

### ISSUE THREAD

**Issue by JeffHoogland** [poppu-mtg/StackIt#73]
Ubuntu 16.04 with python2

Traceback (most recent call last):
  File "StackIt.py", line 34, in <module>
    builder.main(sys.argv[1])
  File "/media/Storage/GitHub/StackIt/StackIt/builder.py", line 440, in main
    lookupScan = scraper.download_scanHexCM(cmdr.name, guid, typeCM)
  File "/media/Storage/GitHub/StackIt/StackIt/scraper.py", line 95, in download_scanHexCM
    os.rename(localname, lookupScan)
OSError: [Errno 18] Invalid cross-device link

**Comment by JeffHoogland** [comment]
Replacing all instances of os.rename with shutil.move (and importing shutil) seems to resolve the issue here.

**Comment by silasary** [comment]
Are you running StackIt off of an external disk?

**Comment by JeffHoogland** [comment]
It shouldn't matter what it is running on, but no, in this case it is running on a hard drive formatted as ext4

**Comment by bakert** [comment]
This fix is in #76
